Google/Google/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('googleApp.urls')),
]

Google/googleApp/urls.py
from django.urls import path
from . import views

app_name = 'googleApp'
urlpatterns = [
    path("",views.home,name = "home"),
    path("terms/",views.terms,name= "terms"),
]

Google/main/urls.py
from django.urls import path
from . import views
app_name = "main"
urlpatterns = [
    path("", views.home_view, name="home_view"),
    path("terms/", views.terms, name="terms"),
]

Google/googleApp/views.py
from django.shortcuts import render
from django.http import HttpRequest,HttpResponse
# Create your views here.

def home(request: HttpRequest):
    return render(request, "googleApp/home.html")


def terms(request:HttpRequest):

    return render(request,"googleApp/terms.html")

Google/main/views.py
from django.shortcuts import render
from django.http import HttpRequest,HttpResponse

def home_view(request:HttpRequest):
    return render(request,"main/index.html")
def terms(request: HttpRequest):
    return render(request, "main/terms.html") 

Google/googleApp/templates/googleApp/home.html
{% extends 'googleApp/inAllPages.html' %}
{% block title %} Google Search {% endblock %}

{% block content %}

<section class="main-section">

    <div class="main-container">
        <img src="/static/images/google-logo.png" class="logo"/>
        <div class="search-container">
            <span class="material-symbols-outlined">search</span>
            <input type="search" placeholder="search.." />
            <img src="/static/images/mircophone.png" class="icon"/>
            <img src="/static/images/camera.png"  class="icon"/>
        </div>
    </div>


    <div class="utils">
        <button>Google Search</button>
        <button>I'm Feeling Lucky</button>
    </div>

    <div class="util-offered">
        Google offered in:  <a href="#">العربية</a>
    </div>


</section>

{% endblock %}

Google/googleApp/templates/googleApp/inAllPages.html
{% load static %}

<html>
<head>
    <title> {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
</head>
<body>
    <div class = "wrapper">
    <nav>
        <a href="#" >Gmail</a>
        <a href="#" >Image</a>
        <span class="material-symbols-outlined">apps</span>
        <button> Sign In</button>
    </nav>

    {% block content %}

    {% endblock %}
    <footer>
        <div class="top-footer">
            Saudi Arabia
        </div>

        <div class="bottom-footer">
            <div>
                <a href="">About</a>
                <a href="">Advertising</a>
                <a href="">Business</a>
                <a href="">How Search works</a>
            </div>
            <div>
                <a href="">Privacy</a>
                <a href="{% url 'googleApp:terms' %}">Terms</a>
                <a href="">Settings</a>
            </div>
        </div>
    </footer>
    </div>
</body>
</html>

Google/googleApp/templates/googleApp/terms.html
{% extends 'googleApp/inAllPages.html' %}
{% load static %}

{% block title %} Terms of Service {% endblock %}

{% block content %}

<section class="main-section">

    <img src="{% static 'images/tos_main_illustration.svg' %}"  class="terms-image"/>
    <div class="terms-paragraph">
    <h1>Google Terms of Service</h1>
    <p>
        Effective 5 January 2022 | Archived versions | Download PDF
        Country version: Saudi Arabia

        What’s covered in these terms
        We know it’s tempting to skip these Terms of Service, but it’s important to establish what you can expect from us as you use Google services, and what we expect from you.
        These Terms of Service reflect the way that Google’s business works, the laws that apply to our company, and certain things that we’ve always believed to be true. As a result, these Terms of Service help define Google’s relationship with you as you interact with our services. For example, these terms include the following topic headings:
            •   What you can expect from us, which describes how we provide and develop our services
            •   What we expect from you, which establishes certain rules for using our services
            •   Content in Google services, which describes the intellectual property rights to the content that you find in our services – whether that content belongs to you, Google or others
            •   In case of problems or disagreements, which describes other legal rights that you have, and what to expect in case someone violates these terms.
        Understanding these terms is important because, by using our services, you’re agreeing to these terms.
        Besides these terms, we also publish a Privacy Policy. Although it’s not part of these terms, we encourage you to read it to better understand how you can update, manage, export and delete your information.
        </p>
</div>

</section>

{% endblock %}

Google/main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&display=swap" rel="stylesheet">
    <title>Document</title>
</head>
<body>
    <div class="wrapper">
        <div class="main-header">
            <a href="#">Gmail</a>
            <a href="#">Images</a>
            <span class="material-symbols-outlined">apps</span>
            <button class="btn">Sign in</button>
        </div>
        <main>
            {% block content %}

            {% endblock %}

        </main>
        
        <footer class="footer">
            {% block footer %}

            {% endblock %}
        </footer>
    </div>
</body>
</html>

Google/main/templates/main/home.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}Google{% endblock %}

{% block content %}
<div class="logo">
    <img width="300" height="100" src="{% static 'main/images/google-logo.png' %}" alt="Google Logo">
</div>
<div class="search-bar">
    <img width="30" height="30" src="{% static 'main/images/search.png' %}" alt="Search">
    <input type="text" placeholder="  Search Google or type a URL">
    <img width="35" height="35" src="{% static 'main/images/camera.png' %}" alt="Camera">
    <img width="35" height="35" src="{% static 'main/images/microphone.png' %}" alt="Microphone">
</div>
<div class="buttons">
    <button>Google Search</button>
    <button>I'm Feeling Lucky</button>
</div>
    <div>
        <p>Google offered in: العربية</p>
    </div>
    <div class="footer-s">
    <span>Saudi Arabia</span>
    </div>
<div class="footer">
    <div>
        <a href="https://about.google/?utm_source=google-SA&utm_medium=referral&utm_campaign=hp-footer&fg=1">About</a>
        <a href="https://ads.google.com/intl/en_sa/home/?subid=ww-ww-et-g-awa-a-g_hpafoot1_1!o2&utm_source=google.com&utm_medium=referral&utm_campaign=google_hpafooter&fg=1">Advertising</a>
        <a href="https://www.google.com.sa/services/?subid=ww-ww-et-g-awa-a-g_hpbfoot1_1!o2&utm_source=google.com&utm_medium=referral&utm_campaign=google_hpbfooter&fg=1">Business</a>
        <a href="https://www.google.com/search/howsearchworks/?fg=1">How Search works</a>
    </div>
    <div>
        <a href="https://policies.google.com/privacy?hl=en-SA&fg=1">Privacy</a>
        <a href="terms/">Terms</a>
        <a href="#">Settings</a>
    </div>
</div>
{% endblock %}

Google/main/templates/main/index.html
{% extends 'main/base.html' %}
{% block content %}

<section class="middle-view">
    <div class="logo">
        <img src="/static/images/google-logo.png" alt="Google Logo">
    </div>
    <div class="search-container">
        <div class="search-box">
            <span class="material-symbols-outlined">search</span>
            <div class="right-nav">
                                         
                <img src="/static/images/mircophone.png" alt="" class="search-icon">
                <img src="/static/images/camera.png" alt="" class="search-icon">
            </div>
        </div>
        <div class="button-container">          
            <button class="button-1">Google Search</button>
            <button class="button-1">I'm Feeling Lucky</button>
        </div>
        <p>Google offered in:  <span style="color: #1d38d3f1; font-size:small"> العربية</span></p>

    </div>
</section>
{% endblock %}

{% block footer %}
<div class="upper-footer">
    <a href="#">Saudi Arabia</a>
</div>
<div class="footer-content">
    <div class="footer-links">
        <a href="#">About</a>
        <a href="#">Advertising</a>
        <a href="#">Business</a>
        <a href="#">How Search Works</a>
    </div>
    <nav class="right-footer">
        <a href="#">Privacy</a>
        <a href="{% url 'main:terms' %}">Terms</a>
        <a href="#">Settings</a>
    </nav>
</div>

{% endblock %}

Google/main/templates/main/terms.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
<div class="terms">
    <img src="{% static 'images/tos_main_illustration.svg' %}" alt="Terms of Service Illustration" class="terms-logo">
    <div class="terms-container">
        <h1>Google Terms of Service</h1>
        <p >Effective 5 January 2022 | <a href="#">Archived versions</a> | <a href="#">Download PDF</a></p>
        <p><a href="">Country version</a>: Saudi Arabia</p>
        <h2>What's covered in these terms</h2>
        <p class="bold">We know it’s tempting to skip these Terms of Service, but it’s important to establish what you can expect from us as you use Google services, and what we expect from you.</p>
        <p>These Terms of Service reflect <a href="#">the way that Google’s business works</a>, the laws that apply to our company, and <a href="">certain things that we’ve always believed to be true</a>. As a result, these Terms of Service help define Google’s relationship with you as you interact with our services. For example, these terms include the following topic headings:</p>
    </div>
</div>
{% endblock %}